name: jmetrics-tests

on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'maven'
      - name: Run tests
        run: mvn -B test --file pom.xml
